export const menuItems = [
    { id: 1, menuItem: "Pancakes", servingTime: "breakfast" },
    { id: 2, menuItem: "Eggs Benedict", servingTime: "breakfast" },
    { id: 3, menuItem: "French Toast", servingTime: "breakfast" },
    { id: 4, menuItem: "Caesar Salad", servingTime: "lunch" },
    { id: 5, menuItem: "Club Sandwich", servingTime: "lunch" },
    { id: 6, menuItem: "Margherita Pizza", servingTime: "lunch" },
    { id: 7, menuItem: "Grilled Salmon", servingTime: "dinner" },
    { id: 8, menuItem: "Steak Frites", servingTime: "dinner" },
    { id: 9, menuItem: "Vegetable Curry", servingTime: "dinner" },
    { id: 10, menuItem: "Spaghetti Bolognese", servingTime: "dinner" },
    { id: 11, menuItem: "Omelette", servingTime: "breakfast" },
    { id: 12, menuItem: "Avocado Toast", servingTime: "breakfast" },
    { id: 13, menuItem: "Greek Salad", servingTime: "lunch" },
    { id: 14, menuItem: "Chicken Caesar Wrap", servingTime: "lunch" },
    { id: 15, menuItem: "Vegetarian Pizza", servingTime: "lunch" },
    { id: 16, menuItem: "Grilled Chicken Breast", servingTime: "dinner" },
    { id: 17, menuItem: "Salmon Fillet", servingTime: "dinner" },
    { id: 18, menuItem: "Beef Stir-Fry", servingTime: "dinner" },
    { id: 19, menuItem: "Pasta Primavera", servingTime: "dinner" },
    { id: 20, menuItem: "Fish Tacos", servingTime: "dinner" }
];
